### ISSUE TITLE
KubeDB fails to deploy Redis

### ISSUE THREAD

**Issue by palkan** [getkuby/kuby-redis#1]
Tried to deploy Redis via Kuby on DO, but failed (see below). Any suggestions?

Kubernetes:  1.21.5-do.0

Config:

```rb
kubernetes do
  add_plugin :kube_db

  add_plugin :redis do
    instance :cable
  end
   
   # ...
end
```

KubeDB log:

```
I1117 15:01:12.721818       1 secure_serving.go:116] Serving securely on [::]:8443
I1117 15:01:12.738220       1 run.go:36] Starting KubeDB controller
I1117 15:01:18.944261       1 xray.go:232] testing ValidatingWebhook using an object with GVR = kubedb.com/v1alpha1, Resource=redises
I1117 15:01:18.993862       1 apiservice.go:58] Patching APIService v1alpha1.validators.kubedb.com with {"metadata":{"annotations":{"admission-webhook.appscode.com/active":"true","admission-webhook.appscode.com/status":""}}}.
I1117 15:02:09.973011       1 redis.go:58] Patching Redis anycable-rails-demo-production/cable-redis with {"metadata":{"finalizers":["kubedb.com"]}}.
E1117 15:02:10.045830       1 workqueue.go:54] selfLink was empty, can't make reference
E1117 15:02:10.046576       1 event.go:259] Could not construct reference to: '&v1alpha1.Redis{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cable-redis", GenerateName:"", Namespace:"anycable-rails-demo-production", SelfLink:"", UID:"224178c0-f49e-4ff7-b1d0-d875f7b77d34", ResourceVersion:"6672", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63772758129, loc:(*time.Location)(0x65dda20)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"kubedb.com/v1alpha1\",\"kind\":\"Redis\",\"metadata\":{\"annotations\":{},\"name\":\"cable-redis\",\"namespace\":\"anycable-rails-demo-production\"},\"spec\":{\"serviceTemplate\":{\"spec\":{\"ports\":[{\"name\":\"memcached\",\"port\":6379}],\"type\":\"NodePort\"}},\"storage\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"1Gi\"}},\"storageClassName\":\"do-block-storage\"},\"storageType\":\"Durable\",\"version\":\"5.0.3-v1\"}}\n"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string{"kubedb.com"}, ClusterName:""}, Spec:v1alpha1.RedisSpec{Version:"5.0.3-v1", Replicas:(*int32)(0xc000682e30), Mode:"Standalone", Cluster:(*v1alpha1.RedisClusterSpec)(nil), StorageType:"Durable", Storage:(*v1.PersistentVolumeClaimSpec)(0xc0022ca540), Monitor:(*v1.AgentSpec)(nil), ConfigSource:(*v1.VolumeSource)(nil), PodTemplate:v1.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Annotations:map[string]string(nil)}, Controller:v1.ObjectMeta{Annotations:map[string]string(nil)}, Spec:v1.PodSpec{ServiceAccountName:"", Args:[]string(nil), NodeSelector:map[string]string(nil), Resources:v1.ResourceRequirements{Limits:v1.ResourceList(nil), Requests:v1.ResourceList(nil)}, Affinity:(*v1.Affinity)(nil), SchedulerName:"", Tolerations:[]v1.Toleration(nil), ImagePullSecrets:[]v1.LocalObjectReference(nil), Env:[]v1.EnvVar(nil), InitContainers:[]v1.Container(nil), PriorityClassName:"", Priority:(*int32)(nil), SecurityContext:(*v1.PodSecurityContext)(nil), LivenessProbe:(*v1.Probe)(nil), ReadinessProbe:(*v1.Probe)(nil), Lifecycle:(*v1.Lifecycle)(nil)}}, ServiceTemplate:v1.ServiceTemplateSpec{ObjectMeta:v1.ObjectMeta{Annotations:map[string]string(nil)}, Spec:v1.ServiceSpec{Ports:[]v1.ServicePort{v1.ServicePort{Name:"memcached", Port:6379, NodePort:0}}, ClusterIP:"", Type:"NodePort", ExternalIPs:[]string(nil), LoadBalancerIP:"", LoadBalancerSourceRanges:[]string(nil), ExternalTrafficPolicy:"", HealthCheckNodePort:0}}, UpdateStrategy:v1.StatefulSetUpdateStrategy{Type:"RollingUpdate", RollingUpdate:(*v1.RollingUpdateStatefulSetStrategy)(nil)}, TerminationPolicy:"Pause"}, Status:v1alpha1.RedisStatus{Phase:"Creating", Reason:"", ObservedGeneration:(*types.IntHash)(nil)}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Warning' 'Failed' 'Fail to be ready Redis: "cable-redis". Reason: selfLink was empty, can't make reference'
E1117 15:02:10.110327       1 worker.go:76] Failed to process key anycable-rails-demo-production/cable-redis. Reason: selfLink was empty, can't make reference
I1117 15:02:10.110545       1 worker.go:80] Error syncing key anycable-rails-demo-production/cable-redis: selfLink was empty, can't make reference
E1117 15:02:10.128493       1 workqueue.go:54] selfLink was empty, can't make reference
```

**Comment by palkan** [comment]
OK, it seems that the KubeDB version we use (0.12.0) isn't compatible with the K8S 1.21.

Recent versions of KubeDB use `v1alpha2` API version (not supported by the gem).

**Comment by camertron** [comment]
Hey @palkan, sorry to have missed this (for some reason it never appeared in my email 😢 )

Sadly I think Kuby is going to have to stop using KubeDB for a variety of reasons. For one thing you now have to obtain a (free) license to use it, which makes the installation process much more difficult (it involves receiving emails, etc). Unfortunately this has prevented me from upgrading it or the supported version of Kubernetes (we're stuck on 1.19). 

As an alternative I'm thinking of trying to adopt [crossplane](https://github.com/crossplane/crossplane) to stand up databases using your chosen cloud provider. Caching systems like memcached and redis are simple/ephemeral enough that Kuby might be able to stand them up itself and avoid using an operator like crossplane or KubeDB.

Would love to hear your thoughts on the matter.

**Comment by camertron** [comment]
See also: https://github.com/getkuby/kuby-core/issues/54

**Comment by palkan** [comment]
> For one thing you now have to obtain a (free) license to use it, which makes the installation process much more difficult

Yeah, not good at all.

> Caching systems like memcached and redis are simple/ephemeral enough that Kuby might be able to stand them up itself and avoid using an operator like crossplane or KubeDB.

Yeah, that makes sense. At least, for very simple installations (like, "gimme a Redis instance w/o any complications like Cluster / Sentinels / whatever".

I think, the key question is where should Kuby responsibility end? Does Kuby meant to be a complete k8s management tool or it should be an application-oriented tool? Deploy, rollback, run a command, easily deploy a sidecar service, etc.

**Comment by camertron** [comment]
> I think, the key question is where should Kuby responsibility end?

Yeah, that's a good question. I'm honestly not sure. When I first thought about what I wanted Kuby to be, I envisioned something as easy to use as Heroku but as simple to install as capistrano. Heroku stands up a Postgres database for you, which is great because it's another thing you don't have to think about. I wanted Kuby to work the same way. I still think figuring out the database for you is something worth doing, simply because the database is such an integral part of pretty much any Rails app. Anyone who's not a hobbyist though is going to want certain guarantees with regard to their database, which Kubernetes can't necessarily fulfill. So it's a tough call.

There are a lot of options, and I keep going back and forth wrestling with the pros and cons. My idea du jour is to only support Postgres (like Heroku does) and stand up instances of CockroachDB, which is cloud-native and Postgres wire-compatible.

Anyway, lots to think about.
